### ISSUE TITLE
Support for Remix v2.0.0

### ISSUE THREAD

**Issue by mateosantosdev** [amimaro/remix-run-snippets#4]
Hello!

Thank you very much for your addon!

Are you interested in support the v2.0.0?

For instance:

```typescript
import type { LoaderFunctionArgs } from '@remix-run/node';
export async function loader({ request }: LoaderFunctionArgs) {
    return null;
}
```

If you want to support it, I can work on a PR.

Regards.

**Comment by amimaro** [comment]
Certainly!
Your contribution to support v2.0.0 is very welcome.
Please go ahead and feel free to work on the PR.
Thank you!
